apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-replicationcontroller
  labels: 
    app: myapp
    tier: backend
spec: 
  template: 
    metadata: 
      name: myapp-replicationcontrollerpods
      labels: 
        app: myapp
        tier: backend
    spec: 
     containers: 
      - name: redis
        image: redis
  replicas: 3
  