apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: 
    app: myapp
    tier: backend
spec:
  template:
    metadata:
      name: myapp-replicaset
      labels: 
        app: myapp
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis
  replicas: 2
  selector: 
    matchLabels: 
      tier: backend