apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  template: 
    metadata:
      name: myapp-deployment
      labels: 
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 2
  selector: 
    matchLabels: 
      tier: frontend